- checking all test files and code examples. - classes need documentation - issues with a few docs
── R CMD check results ──────── collinear 2.1.0 ────
Duration: 1m 27s

❯ checking examples ... ERROR
  Running examples in ‘collinear-Ex.R’ failed
  The error most likely occurred in:

  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: cor_df
  > ### Title: Pairwise Correlation Data Frame
  > ### Aliases: cor_df cor_numeric_vs_numeric cor_numeric_vs_categorical
  > ###   cor_categorical_vs_categorical
  >
  > ### ** Examples
  >
  >   data(vi)
  >
  >   #subset to speed-up example
  >   vi <- vi[1:1000, ]
  >
  >   #predictors
  >   predictors = c(
  +     "koppen_zone", #character
  +     "soil_type", #factor
  +     "topo_elevation", #numeric
  +     "soil_temperature_mean" #numeric
  +   )
  >
  >   #OPTIONAL: parallelization setup
  >   # future::plan(
  >   #   future::multisession,
  >   #   workers = 2
  >   # )
  >
  >   #OPTIONAL: progress bar
  >   # progressr::handlers(global = TRUE)
  >
  >   #without preference order
  >   selected_predictors <- cor_select(
  +     df = vi,
  +     predictors = predictors,
  +     preference_order = NULL,
  +     max_cor = 0.75
  +   )

  collinear::cor_select(): ranking predictors from lower to higher multicollinearity.

  collinear::cor_select(): selected predictors:
   - topo_elevation
   - soil_type
   - koppen_zone
  >
  >
  >   #with custom preference order
  >   selected_predictors <- cor_select(
  +     df = vi,
  +     predictors = predictors,
  +     preference_order = c(
  +       "soil_temperature_mean",
  +       "soil_type"
  +     ),
  +     max_cor = 0.75
  +   )

  collinear::cor_select(): selected predictors:
   - soil_temperature_mean
   - soil_type
   - topo_elevation
  >
  >
  >   #with automated preference order
  >   df_preference <- preference_order(
  +     df = vi,
  +     response = "vi_numeric",
  +     predictors = predictors
  +   )

  collinear::f_auto(): selected function 'f_r2_rf()' for response 'vi_numeric'.
  >
  >   selected_predictors <- cor_select(
  +     df = df,
  +     predictors = predictors,
  +     preference_order = df_preference,
  +     max_cor = 0.75
  +   )
  Error:
  collinear::cor_select(): argument 'df' must be of class 'data .frame' or coercible to 'data.frame'.
  Execution halted

❯ checking S3 generic/method consistency ... WARNING
  print:
    function(x, ...)
  print.collinear_selection:
    function(x, n)

  print:
    function(x, ...)
  print.collinear_arguments:
    function(x, n)

  print:
    function(x, ...)
  print.collinear_output:
    function(x, n)

  summary:
    function(object, ...)
  summary.collinear_selection:
    function(x)

  summary:
    function(object, ...)
  summary.collinear_output:
    function(x)
  See section ‘Generic functions and methods’ in the ‘Writing R
  Extensions’ manual.

❯ checking Rd cross-references ... WARNING
  Missing link(s) in Rd file 'print.collinear_output.Rd':
    ‘collinear_output’

  See section 'Cross-references' in the 'Writing R Extensions' manual.

  Found the following Rd file(s) with Rd \link{} targets missing package
  anchors:
    print.collinear_output.Rd: collinear_output
  Please provide package anchors for all Rd \link{} targets not in the
  package itself and the base packages.

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in Rd file 'build.collinear_selection.Rd'
    ‘selection’

  Undocumented arguments in Rd file 'validate_arg_df_not_null.Rd'
    ‘function_name’

  Undocumented arguments in Rd file 'validate_arg_encoding_method.Rd'
    ‘overwrite’

  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking package namespace information ... NOTE
  Found export directive that requires package ‘methods’:
    ‘exportClasses’
  Remove all such namespace directives (if obsolete) or ensure that the
  DESCRIPTION Depends or Imports field contains ‘methods’.

❯ checking Rd line widths ... NOTE
  Rd file 'collinear.Rd':
    \examples lines wider than 100 characters:
         ##missing predictors in preference_order due to multicollinearity with predictors with a higher preference

  These lines will be truncated in the PDF manual.

1 error ✖ | 3 warnings ✖ | 2 notes ✖
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.